d /run/tompanel 0750 tompanel tompanel -
d /var/lib/tompanel 0750 tompanel tompanel -
d /var/backups/tompanel 0750 tompanel tompanel -
d /srv/tompanel 0755 root root -
d /srv/tompanel/sites 0755 root root -
d /srv/tompanel/quarantine 0700 root root -
