package apps

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"math/big"
	"strings"
)

// WordPressPolicy controls independent update channels.
type WordPressPolicy struct {
	MinorCore bool `json:"minor_core"`
	MajorCore bool `json:"major_core"`
	Plugins   bool `json:"plugins"`
	Themes    bool `json:"themes"`
}

// DefaultWordPressPolicy enables security and minor updates only.
func DefaultWordPressPolicy() WordPressPolicy {
	return WordPressPolicy{MinorCore: true, MajorCore: false, Plugins: false, Themes: false}
}

// WordPressInstallInput carries everything one installation needs. Secrets
// travel to WP-CLI through stdin prompts or mode-0600 files, never argv.
type WordPressInstallInput struct {
	SiteID        string          `json:"-"`
	SiteURL       string          `json:"site_url"`
	Database      string          `json:"database"`
	DBUser        string          `json:"db_user"`
	DBPassword    string          `json:"-"`
	AdminUser     string          `json:"admin_user"`
	AdminEmail    string          `json:"admin_email"`
	AdminPassword string          `json:"-"`
	Title         string          `json:"title"`
	Policy        WordPressPolicy `json:"policy"`
}

// WPCLICall is one exact WP-CLI invocation: binary, argv, protected stdin.
type WPCLICall struct {
	Binary string
	Args   []string
	Stdin  []byte
}

var (
	ErrInvalidInput       = errors.New("wordpress input is invalid")
	wpCLIBinary           = "/usr/local/bin/wp"
	wpAdminPasswordPrompt = "admin_password"
	wpDBPasswordPrompt    = "dbpass"
	secretAlphabet        = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#%^*-_=+"
	secretLength          = 28
)

// BuildWordPressInstallCall returns the exact WP-CLI argument array and
// protected stdin payload for the core installation flow without running it.
func BuildWordPressInstallCall(input WordPressInstallInput) ([]WPCLICall, error) {
	if err := validateInstallInput(input); err != nil {
		return nil, err
	}
	path := sitePath(input.SiteID)
	calls := []WPCLICall{
		{Binary: wpCLIBinary, Args: []string{"--path=" + path, "core", "download", "--version=" + WordPressCoreVersion, "--force"}},
		{Binary: wpCLIBinary, Args: []string{
			"--path=" + path, "config", "create",
			"--dbname=" + input.Database, "--dbuser=" + input.DBUser,
			"--dbhost=localhost:/run/mysqld/mysqld.sock",
			"--prompt=" + wpDBPasswordPrompt,
		}, Stdin: []byte(input.DBPassword + "\n")},
		{Binary: wpCLIBinary, Args: []string{
			"--path=" + path, "core", "install",
			"--url=" + input.SiteURL, "--title=" + input.Title,
			"--admin_user=" + input.AdminUser, "--admin_email=" + input.AdminEmail,
			"--skip-email", "--prompt=" + wpAdminPasswordPrompt,
		}, Stdin: []byte(input.AdminPassword + "\n")},
		{Binary: wpCLIBinary, Args: []string{"--path=" + path, "core", "verify-checksums"}},
		{Binary: wpCLIBinary, Args: []string{"--path=" + path, "config", "set", "WP_AUTO_UPDATE_CORE", wordpressAutoUpdateConstant(input.Policy)}},
		{Binary: wpCLIBinary, Args: []string{"--path=" + path, "config", "set", "DISALLOW_FILE_EDIT", "true", "--raw"}},
		{Binary: wpCLIBinary, Args: []string{"--path=" + path, "config", "set", "FORCE_SSL_ADMIN", "true"}},
	}
	return calls, nil
}

func wordpressAutoUpdateConstant(policy WordPressPolicy) string {
	switch {
	case policy.MajorCore:
		return "true"
	case policy.MinorCore:
		return "minor"
	default:
		return "false"
	}
}

// BuildWordPressUpdateCall returns the update sequence with a pre-update
// export so a failed update can be rolled back.
func BuildWordPressUpdateCall(input WordPressInstallInput) ([]WPCLICall, error) {
	if err := validateInstallInput(input); err != nil {
		return nil, err
	}
	path := sitePath(input.SiteID)
	calls := []WPCLICall{
		{Binary: wpCLIBinary, Args: []string{"--path=" + path, "db", "export", "../.tompanel/pre-update.sql"}},
		{Binary: wpCLIBinary, Args: []string{"--path=" + path, "core", "update"}},
	}
	if input.Policy.Plugins {
		calls = append(calls, WPCLICall{Binary: wpCLIBinary, Args: []string{"--path=" + path, "plugin", "update", "--all"}})
	}
	if input.Policy.Themes {
		calls = append(calls, WPCLICall{Binary: wpCLIBinary, Args: []string{"--path=" + path, "theme", "update", "--all"}})
	}
	return calls, nil
}

func validateInstallInput(input WordPressInstallInput) error {
	if !validSiteID(input.SiteID) {
		return fmt.Errorf("%w: site id", ErrInvalidInput)
	}
	if len(input.DBPassword) < 16 || len(input.AdminPassword) < 16 {
		return fmt.Errorf("%w: secrets must be generated by the panel", ErrInvalidInput)
	}
	if strings.ContainsAny(input.DBPassword, "\n\r") || strings.ContainsAny(input.AdminPassword, "\n\r") {
		return fmt.Errorf("%w: secrets must be single line", ErrInvalidInput)
	}
	if input.Database == "" || input.DBUser == "" || input.AdminUser == "" || input.AdminEmail == "" || input.SiteURL == "" {
		return fmt.Errorf("%w: required fields missing", ErrInvalidInput)
	}
	return nil
}

func validSiteID(id string) bool {
	if len(id) != 32 {
		return false
	}
	for _, character := range id {
		if character >= '0' && character <= '9' || character >= 'a' && character <= 'f' {
			continue
		}
		return false
	}
	return true
}

func sitePath(siteID string) string {
	return "/srv/tompanel/sites/" + siteID + "/public"
}

// GenerateWordPressSecrets mints an administrator password and salts.
func GenerateWordPressSecrets() (password string, err error) {
	var builder strings.Builder
	for i := 0; i < secretLength; i++ {
		index, err := rand.Int(rand.Reader, big.NewInt(int64(len(secretAlphabet))))
		if err != nil {
			return "", fmt.Errorf("generate wordpress secret: %w", err)
		}
		builder.WriteByte(secretAlphabet[index.Int64()])
	}
	return builder.String(), nil
}

// WordPressCoreVersion is the pinned release installed by TomPanel.
const WordPressCoreVersion = "6.8"

func newAppID() (string, error) {
	var value [16]byte
	if _, err := rand.Read(value[:]); err != nil {
		return "", fmt.Errorf("generate ID: %w", err)
	}
	return hex.EncodeToString(value[:]), nil
}
